import {defineField, defineType} from 'sanity'

export const productMetaType = defineType({
  name: 'productMeta',
  title: 'Product Meta',
  type: 'document',
  fields: [
    defineField({
      name: 'product',
      title: 'Product',
      type: 'reference',
      to: [{type: 'product'}],
    }),
    defineField({
      name: 'salesCountToday',
      title: 'Sales Count Today',
      type: 'number',
      description: 'Number of sales recorded today.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesValueToday',
      title: 'Sales Value Today',
      type: 'number',
      description: 'Total revenue from sales today.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesCountLast7Days',
      title: 'Sales Count (Last 7 Days)',
      type: 'number',
      description: 'Number of sales recorded over the last 7 days.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesValueLast7Days',
      title: 'Sales Value (Last 7 Days)',
      type: 'number',
      description: 'Total revenue from sales over the last 7 days.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesCountLast30Days',
      title: 'Sales Count (Last 30 Days)',
      type: 'number',
      description: 'Number of sales recorded over the last 30 days.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesValueLast30Days',
      title: 'Sales Value (Last 30 Days)',
      type: 'number',
      description: 'Total revenue from sales over the last 30 days.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesCountTotal',
      title: 'Sales Count (Total)',
      type: 'number',
      description: 'Number of sales recorded over total.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'salesValueTotal',
      title: 'Sales Value (Total)',
      type: 'number',
      description: 'Total revenue from sales over total.',
      initialValue: 0,
      validation: (rule: any) => rule.min(0),
    }),
    defineField({
      name: 'lastSaleDate',
      title: 'Last Sale Date',
      type: 'datetime',
      description: 'Timestamp of the most recent sale for this product.',
    }),
  ],
})
